
services:
  mongo:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  backend:
    build: ./control-acceso-backend
    container_name: control-acceso-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./control-acceso-backend/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
